### ISSUE TITLE
Bug: callback called multiple times

### ISSUE THREAD

**Issue by Almenon** [bitfasching/node-line-transform-stream#2] opened 2021-03-21 18:48 UTC
Relevant code:
```javascript
        lines.forEach( ( line ) =>
        {
            try
            {
                // pass line to callback, transform it and add line-break back
                output += this.transformCallback( line ) + '\r\n'
            }
            catch ( error )
            {
                // catch processing errors and emit as stream error
                callback( error )
            }
        })
```

As you can see above the callback can possibly be called multiple times, once for each line.
But according to node docs "The callback function must be called only when the current chunk is completely consumed"

I'm not quite sure what the fix would be here. You could either:
1. Append all the errors to a big string and do the callback at the end with the string
2. only call the callback once
3. forgo the error callback alltogether (not sure what it's used for anyways)

**Comment by Almenon** [comment] 2021-03-21 18:48
Example error:
```
     Uncaught Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
      at LineTransformStream.afterTransform (_stream_transform.js:94:31)
      at C:\dev\python-shell\node_modules\line-transform-stream\line-transform-stream.js:76:17
      at Array.forEach (<anonymous>)
      at LineTransformStream._transform (node_modules\line-transform-stream\line-transform-stream.js:66:15)
      at LineTransformStream.Transform._read (_stream_transform.js:205:10)
      at LineTransformStream.Transform._write (_stream_transform.js:193:12)
      at writeOrBuffer (_stream_writable.js:352:12)
      at LineTransformStream.Writable.write (_stream_writable.js:303:10)
      at Socket.ondata (_stream_readable.js:719:22)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:280:11)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by bitfasching** [comment] 2021-07-27 11:50
Hi @Almenon, yes, the callback will be called for every complete line in the current chunk, this is intended behavior. Passing more than one line to the callback would void the whole idea of this transform stream class.

Thank you for pointing out that the Node docs oppose this practice. I'm not sure if this statement was there back when I implemented the class. Anyway, I don't see how this can be fixed without passing more than one line to the callback. Frankly, I'm a bit surprised that Node wouldn't allow multiple calls to the callback in the first place.

Since 2/3 of your mitigation proposals refer to error handling (while the multiple calls statement in the docs isn't limited to errors), did you narrow it down to error passing being the culprit? I've been using this class a lot and never ran into this. Can you provide a minimum working example to reproduce the above error?

**Closed as completed** 2022-11-01 16:43 UTC

**Comment by bitfasching** [comment] 2022-11-01 16:56
Hi @Almenon, sorry, I misunderstood which callback you were referring to. Node's stream callback must indeed only be called once.

**Comment by Almenon** [comment] 2022-11-02 04:23
Thanks! No worries
